receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  jaeger_grpc:
    endpoint: jaeger-all-in-one:14250

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [jaeger_grpc]
      processors: [batch, queued_retry]
