name: Core Contrib Test

on:
  push:
    branches-ignore:
    - 'release/*'
    - 'otelbot/*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  contrib_0:
    uses: open-telemetry/opentelemetry-python-contrib/.github/workflows/core_contrib_test_0.yml@main
    with:
      CORE_REPO_SHA: ${{ github.sha }}
      # DO NOT SUBMIT: Testing https://github.com/open-telemetry/opentelemetry-python-contrib/pull/4165
      CONTRIB_REPO_SHA: d6b916049d9c1c7a3664a15a5cfbef722265dbd0
